import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Image from "next/image";
import Footer from "@/component/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="selection:bg-red-700 bg-white text-black font-sans items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 s:p-2">
          <h1 className="text-4xl">DBDle -- Privacy Policy</h1>
          Content Used From
This website uses materials (including images and perk descriptions) from most of the articles on the Dead by Daylight wiki at Fandom and is licensed under the CC BY-NC-SA (Attribution-NonCommercial-ShareAlike) License.

Bug and Security Reports
If you find any security vulnerabilities or bugs please contact us at hello@example.com

Cookie Policy
How do we use cookies?
Thanks for playing DBDle! Go back to playing right here.
        </div>
      </body>
    </html>
  );
}
