const splash = {
  step:13,
  number_of_tries:30,
  width:512
}

const nameVariations = [
  {from:"The Nemesis T-Type",to:"The Nemesis"},
  {from:"The Frank, Julie, Susie, Joey",to:"The Legion"},
  {from:"The Charles Lee Ray",to:"The Good Guy"},
  {from:"The Jeffrey Hawk",to:"The Clown"},
  {from:"The Danny Johnson",to:"The Ghost Face"},
  {from:"Bill Overbeck",to:'William "Bill" Overbeck'},
  {from:"Leon Scott Kennedy",to:'Leon S. Kennedy'},
  {from:"Kate Denson's",to:"Kate Denson"},
  {from:"Trevor",to:"Trevor Belmont"},
  {from:"Troupe",to:'Aestri Yazar & Baermar Uraz'},
  {from:"Baermar",to:'Aestri Yazar & Baermar Uraz'},
  {from:"Aestri",to:"Aestri Yazar & Baermar Uraz"},
  {from:"Jeff",to:"Jeff Johansen"},
  {from:"Detective David Tapp",to:"Detective Tapp"},
  {from:"Sable",to:"Sable Ward"},
  {from:"Final Journal Entry",to:"The Unknown"},
  {from:"Anonymous Testimony",to:"The Unknown"},
  {from:"Ji-Woon Hak",to:"The Trickster"},
  {from:"Amanda Young",to:"The Pig"},
  {from:"Herman Carter",to:"The Doctor"},
  {from:"Adriana Imai",to:"The Skull Merchant"},
  {from:"Carmina Mora",to:"The Artist"},
  {from:"Dracula",to:"The Dark Lord"},
  {from:"HUX-A7-13",to:"The Singularity"},
  {from:"Portia Maye",to:"The Houndmaster"},
  {from:"Freddy Krueger",to:"The Nightmare"},
  {from:"Journal of Talbot Grimes",to:"The Blight"},
  {from:"Chucky",to:"The Good Guy"},
  {from:"Tarhos Kovács",to:"The Knight"},
  {from:"Vecna",to:"The Lich"},
  {from:"Unknown",to:"The Unknown"},
  {from:"Charlotte Deshayes",to:"The Twins"},
  {from:"Caleb Quinn",to:"The Deathslinger"},
  {from:"(The Tablet of Adiris",to:"The Plague"},
  {from:"Girl in the Shadow by Carmina Mora",to:"The Artist"},
  {from:"Notebook",to:"The Unknown"},
]
const invalidNames = [
    "Nikki",
    "Return",
    "Departure",
    "Murf",
    "Sujan",
    "Dylan",
    "Clyde",
    "Pauline Stamper",
    "Aizeyu",
    "Jordan Rois",
    "Andy",
    "Renjiro's Doctrine 12:5",
    "OSS Report",
    "Robert Kendo",
    "Nubbins Sawyer",
    "Carlos Oliveira",
    "Renjiro's Doctrine 4:9",
    "The Prison Warden",
    "Sonhadores Sombrios",
    "Franklin Hardesty",
    "Dr Sam Loomis",
    "Sassy",
    "Dallas",
    "Drayton Sawyer",
    "Renjiro's Doctrine 6:3",
    "Hawkins National Laboratory",
    "Otto Stamper",
    "A Guide to Art &amp; Process (1961)",
    "(Hymn of Praise",
    "Vigo",
    "Ash"
]
module.exports = {nameVariations,invalidNames,splash}