import type { Metadata } from "next";
import { categories } from "@/util/constants";
import IconButton from "@/component/button/icon";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return [
    <div className="flex gap-4" key={1}>
        <ul className="flex gap-2">
            {categories.map(category => (
                <IconButton key={category.title} link={category.link} icon="/imgs/logos/IconHelp_perks.webp"/>
            ))}
        </ul>
        <div>

        </div>
    </div>,
    children
  ]
}
