import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Image from "next/image";
import Footer from "@/component/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="selection:bg-red-700 font-sans items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 s:p-2">
          <Image src={"/imgs/logos/dbd_bg.jpg"} alt="dead by daylight background" height={1733} width={2560} className="h-[115%] fixed top-0 -z-20 object-cover"/>
          <main className="flex flex-col gap-[32px] items-center s:w-[100%] sm:w-[50%] md:w-[40%] mx-auto">
            <Image src={"/imgs/logos/Deadbydaylight_logo.webp"} alt="dead by daylight logo" height={238} width={736} className="w-full"/>
            {children}
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
